services:
  nginx:
    build: .
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html:ro
    restart: unless-stopped
